#!/usr/bin/env bash
# Runs a single LeoClaw cron job via claude -p.
# Called by launchd agents generated by compile-crons.ts.
#
# Usage: run-cron.sh <cron-name>

set -euo pipefail

CRON_NAME="${1:?Usage: run-cron.sh <cron-name>}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE="$ROOT_DIR/workspace"
CRON_FILE="$WORKSPACE/crons/${CRON_NAME}.md"
LOG_DIR="$WORKSPACE/tmp/cron-logs"

mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${CRON_NAME}.log"

# Log rotation: truncate if >100KB (stat -f%z is macOS-specific; use stat -c%s on Linux)
if [[ -f "$LOG_FILE" ]] && [[ $(stat -f%z "$LOG_FILE" 2>/dev/null || echo 0) -gt 102400 ]]; then
  tail -c 51200 "$LOG_FILE" > "$LOG_FILE.tmp" && mv "$LOG_FILE.tmp" "$LOG_FILE"
fi

exec >> "$LOG_FILE" 2>&1

echo ""
echo "=== $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="

if [[ ! -f "$CRON_FILE" ]]; then
  echo "ERROR: Cron file not found: $CRON_FILE"
  exit 1
fi

# Environment
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

# Telegram bot token from keychain
if [[ -z "${TELEGRAM_BOT_TOKEN:-}" ]]; then
  KEYCHAIN_SERVICE="${LEO_KEYCHAIN_SERVICE:-leoclaw.telegram_bot_token}"
  KEYCHAIN_ACCOUNT="${LEO_KEYCHAIN_ACCOUNT:-${USER:-${LOGNAME:-$(whoami)}}}"
  TELEGRAM_BOT_TOKEN="$(security find-generic-password -a "$KEYCHAIN_ACCOUNT" -s "$KEYCHAIN_SERVICE" -w 2>/dev/null)" || {
    echo "ERROR: Failed to get bot token from keychain"
    exit 1
  }
  export TELEGRAM_BOT_TOKEN
fi

export AGENT_BROWSER_PROFILE="$ROOT_DIR/workspace/secrets/browser-profile"
export CLAUDE_CODE_ENTRYPOINT="cli"

# Extract chat_id from YAML frontmatter
CHAT_ID=$(awk '
  /^---$/ { count++; next }
  count == 1 && /^chat_id:/ {
    val = $0
    sub(/^chat_id:[[:space:]]*/, "", val)
    gsub(/["'"'"']/, "", val)
    print val
    exit
  }
' "$CRON_FILE")

if [[ -z "$CHAT_ID" ]]; then
  echo "ERROR: No chat_id in frontmatter"
  exit 1
fi

# R10: Validate chat_id is numeric (prevents path traversal and injection)
if ! [[ "$CHAT_ID" =~ ^-?[0-9]+$ ]]; then
  echo "ERROR: Invalid chat_id (must be numeric): $CHAT_ID"
  exit 1
fi

# Check enabled flag
ENABLED=$(awk '
  /^---$/ { count++; next }
  count == 1 && /^enabled:/ {
    val = $0
    sub(/^enabled:[[:space:]]*/, "", val)
    gsub(/["'"'"']/, "", val)
    print val
    exit
  }
' "$CRON_FILE")

if [[ "$ENABLED" == "false" ]]; then
  echo "SKIP: Cron is disabled"
  exit 0
fi

# Extract prompt body (everything after second ---)
PROMPT_BODY=$(awk '
  /^---$/ { count++; next }
  count >= 2 { print }
' "$CRON_FILE")

# Build prompt
FULL_PROMPT="[chat_id: ${CHAT_ID}, cron: ${CRON_NAME}]

Use the telegram MCP tools to send your response directly to chat_id ${CHAT_ID}.

${PROMPT_BODY}"

# Claude invocation — generate a session ID so replies can --resume this cron's context
SESSION_ID="$(uuidgen | tr '[:upper:]' '[:lower:]')"
export LEO_SESSION_ID="$SESSION_ID"

CLAUDE_PATH="${LEO_CLAUDE_PATH:-claude}"
CLAUDE_ARGS=(-p "$FULL_PROMPT" --output-format text --session-id "$SESSION_ID")

if [[ "${LEO_DANGEROUSLY_SKIP_PERMISSIONS:-}" == "true" ]] || [[ "${LEO_DANGEROUSLY_SKIP_PERMISSIONS:-}" == "1" ]]; then
  CLAUDE_ARGS+=(--dangerously-skip-permissions)
fi

echo "Running: ${CRON_NAME} (${#FULL_PROMPT} chars prompt)"

cd "$WORKSPACE"
START=$(date +%s)

"$CLAUDE_PATH" "${CLAUDE_ARGS[@]}" || {
  echo "ERROR: Claude exited with code $?"
}

END=$(date +%s)
echo "Done in $((END - START))s"
